[package]
name = "norris"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.26"
log = "0.4.19"
poise = "0.5.5"
serde = { version = "1.0.164", features = ["derive"] }
simplelog = "0.12.1"
sqlx = { version = "0.6.3", features = ["mysql", "runtime-tokio-rustls"] }
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["rt-multi-thread"] }
toml = "0.7.5"
