volumes:
  my-db:

services:
  norris:
    image: Carnagion/norris:latest
    container_name: norris
    restart: always
    networks:
      - default
    volumes:
      - /path/to/config/file:/app/norris.toml
  norrisdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'norrisdb'
      MYSQL_USER: 'norris'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - default
    volumes:
      - norrisdb_data:/var/lib/mysql
      - /path/to/init.sql:/docker-entrypoint-initdb.d/init.sql

