volumes:
  norrisdb_data:

services:
  norris:
    image: Carnagion/norris:latest
    container_name: norris
    restart: always
    networks:
      - default
    volumes:
      - /path/to/norris.toml:/app/norris.toml
    depends_on:
      - norrisdb
  norrisdb:
    image: mysql:8.0
    container_name: norrisdb
    restart: always
    environment:
      MYSQL_DATABASE: 'norrisdb'
      MYSQL_USER: 'norris'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    command: --ssl=0
    networks:
      - default
    volumes:
      - norrisdb_data:/var/lib/mysql
      - /path/to/init.sql:/docker-entrypoint-initdb.d/init.sql
