CREATE TABLE `registrations` (
  `user_id` bigint(20) unsigned NOT NULL,
  `status` enum('UNREGISTERED','STARTED','NAME_ENTERED','KIND_FOUND','VERIFIED','PRONOUNS_PICKED','REGISTERED','FAILED') NOT NULL DEFAULT 'UNREGISTERED',
  `name` varchar(1024) DEFAULT NULL,
  `kind` enum('UNDERGRAD','POSTGRAD','MENTOR','SENIOR_MENTOR','HONORARY_MENTOR','FACULTY') DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf16 COLLATE=utf16_unicode_ci;

CREATE TABLE `registrations` (
  `user_id` bigint(20) unsigned NOT NULL,
  `status` enum('UNREGISTERED','STARTED','NAME_ENTERED','KIND_FOUND','VERIFIED','PRONOUNS_PICKED','REGISTERED','FAILED') NOT NULL DEFAULT 'UNREGISTERED',
  `name` varchar(1024) DEFAULT NULL,
  `kind` enum('UNDERGRAD','POSTGRAD','MENTOR','SENIOR_MENTOR','HONORARY_MENTOR','FACULTY') DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf16 COLLATE=utf16_unicode_ci;