target-version = "py311"

extend-select = [
    "N", # naming conventions as outlined by the PEP 8 style guide
    "W", # spacing and indentation
    "I", # consistent import order
    "D", # docstring comments
    "ANN", # type annotations
    "UP", # latest Python features
    "COM", # trailing commas
    "ISC", # implicit string concatenation
    "BLE", "TRY", "RSE", # good exception raising practices
    "ASYNC", # good async practices
    "S", # security
    "C4", # list and dict comprehensions
    "RET", # good return practices
    "SIM", # simplify code
    "ERA", # get rid of commented out code
    "RUF", # miscellaneous rules
]

ignore = [
    "ANN1", # self and cls should not need a type annotation
    "D1", # TODO: un-ignore once we actually have docstrings
]

[per-file-ignores]
"__init__.py" = ["F401"] # re-exports are common in package initialisers