users: {
    shape: sql_table
    id: "bigint unsigned" {
        constraint: [
            "primary key";
            "not null";
            "auto increment";
        ]
    }
    name: "varchar (1024)" {
        constraint: [
            "not null";
        ]
    }
    kind: "enum (\"UNDERGRAD\", \"POSTGRAD\", \"MENTOR\", \"SENIOR_MENTOR\", \"HONORARY_MENTOR\", \"FACULTY\")" {
        constraint: [
            "not null";
        ]
    }
    registered_user_id: "bigint unsigned"
}

registrations: {
    shape: sql_table
    user_id: "bigint unsigned" {
        constraint: [
            "primary key";
            "not null";
        ]
    }
    status: "enum (\"UNREGISTERED\", \"STARTED\", \"NAME_ENTERED\", \"KIND_FOUND\", \"VERIFIED\", \"PRONOUNS_PICKED\", \"REGISTERED\", \"FAILED\")" {
        constraint: [
            "not null";
        ]
    }
    name: "varchar (1024)"
    kind: "enum (\"UNDERGRAD\", \"POSTGRAD\", \"MENTOR\", \"SENIOR_MENTOR\", \"HONORARY_MENTOR\", \"FACULTY\")"
}