//! Discord event handling functions and helpers.

use poise::{serenity_prelude as serenity, Event};

use serenity::*;

use crate::prelude::*;

mod guild_member_addition;
pub use guild_member_addition::*;

mod guild_member_removal;
pub use guild_member_removal::*;

mod component_interaction;
pub use component_interaction::*;

mod message;
pub use message::*;

/// Handles all Discord [`Event`]s, ignoring the ones that are not required for the bot's functionality.
///
/// Events and interactions generated by other bots are always ignored.
pub async fn event_handler(
    context: &Context,
    event: &Event<'_>,
    bot_data: &BotData,
) -> BotResult<()> {
    match event {
        Event::GuildMemberAddition { new_member } if !new_member.user.bot => {
            guild_member_added(context, new_member, bot_data).await
        },
        Event::GuildMemberRemoval { user, .. } if !user.bot => {
            guild_member_removed(context, user, bot_data).await
        },
        Event::InteractionCreate {
            interaction: Interaction::MessageComponent(component_interaction),
        } if !component_interaction.user.bot => {
            message_component_interacted(context, component_interaction, bot_data).await
        },
        Event::Message { new_message } if new_message.is_private() && !new_message.author.bot => {
            messaged(context, new_message, bot_data).await
        },
        _ => Ok(()),
    }
}
