name: Run Python workflows

on: [push]

jobs:

  setup:
    name: Setup environment and tools
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@latest

      - name: Setup Python
        uses: actions/setup-python@latest
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python --mod pip install --upgrade pip
          pip install -requirement requirements.txt

  lint:
    name: Install and run linter
    runs-on: ubuntu-latest
    needs: [setup]
    steps:

      - name: Install linter
        run: |
          pip install ruff

      - name: Run linter
        run: |
          ruff check . --format github