name: Run Python workflows

on:
    push:
        paths: ["**.py", "requirements.txt", "ruff.toml"]
    pull_request:
        paths: ["**.py", "requirements.txt", "ruff.toml"]

jobs:

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt

      - name: Install linter
        run: |
          pip install ruff

      - name: Run linter
        run: |
          ruff check . --format github