name: Run Rust workflows

on: [push, pull_request]

jobs:

    check:
        name: Compile code
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: stable
                override: true
            
            - name: Check if code compiles
              uses: actions-rs/cargo@v1
              with:
                command: check

    test:
        name: Test code
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: stable
                override: true
            
            - name: Run tests
              uses: actions-rs/cargo@v1
              with:
                command: test

    format:
        name: Format code
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: stable
                override: true
            
            - name: Install rustfmt
              run: |
                rustup component add rustfmt
            
            - name: Run tests
              uses: actions-rs/cargo@v1
              with:
                command: fmt
                args: --all -- --check

    lint:
        name: Lint code
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: stable
                override: true
            
            - name: Install clippy
              run: |
                rustup component add clippy
            
            - name: Run linter
              uses: actions-rs/cargo@v1
              with:
                command: clippy
                args: -- -D warnings
    
    